version: '3.0'

services:
  grafana:
    container_name: 'app-with-scenes'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.5.0}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/app-with-scenes
      - ./provisioning:/etc/grafana/provisioning
      - ./provisioning/custom.ini:/etc/grafana/grafana.ini
