version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    reviewers:
      - "grafana/plugins-platform"

  - package-ecosystem: "npm"
    directory: "/app-basic"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "grafana/plugins-platform-frontend"

  - package-ecosystem: "npm"
    directory: "/app-with-dashboards"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "grafana/plugins-platform-frontend"

  - package-ecosystem: "npm"
    directory: "/datasource-basic"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "grafana/plugins-platform-frontend"

  - package-ecosystem: "npm"
    directory: "/datasource-http"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "grafana/plugins-platform-frontend"
  
  
  - package-ecosystem: "npm"
    directory: "/datasource-http-backend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "grafana/plugins-platform-frontend"
  
  - package-ecosystem: "npm"
    directory: "/datasource-streaming-websocket"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "grafana/plugins-platform-frontend"
  
  - package-ecosystem: "npm"
    directory: "/panel-basic"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "grafana/plugins-platform-frontend"

  - package-ecosystem: "npm"
    directory: "/panel-datalinks"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "grafana/plugins-platform-frontend"
  
  - package-ecosystem: "npm"
    directory: "/panel-flot"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "grafana/plugins-platform-frontend"

  - package-ecosystem: "npm"
    directory: "/panel-frame-select"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "grafana/plugins-platform-frontend"
  
  - package-ecosystem: "npm"
    directory: "/panel-plotly"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "grafana/plugins-platform-frontend"
  
  - package-ecosystem: "npm"
    directory: "/panel-scatterplot"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "grafana/plugins-platform-frontend"    
  
  - package-ecosystem: "npm"
    directory: "/panel-visx"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "grafana/plugins-platform-frontend"        