version: '3.0'

services:
  grafana:
    container_name: 'grafana-appwithserviceaccount-app'
    build:
      context: ./.config
      args:
        # Points to an unreleased v10.1 version of Grafana
        grafana_version: ${GRAFANA_VERSION:-10.0.3}
    ports:
      - 3000:3000/tcp
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=externalServiceAuth externalServiceAccounts
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-appwithserviceaccount-app
      - ./provisioning:/etc/grafana/provisioning
